name    'amara-memcached'
version '0.0.1'
source 'UNKNOWN'
author 'Amara <dev@pculture.org>'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
