# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  # default OS is ubuntu 12.04 LTS amd64
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.share_folder "puppet_modules", "/mnt/puppet-modules", "../puppetmaster/modules"

  config.vm.define :lb do |lb_config|
    lb_config.vm.host_name = "lb.local"
    lb_config.vm.network :hostonly, "10.10.10.105"
    lb_config.vm.forward_port 80, 8180 # http
    lb_config.vm.forward_port 443, 8143 # https
    lb_config.vm.provision :shell, :path => "bootstrap.sh"
  end

  config.vm.define :util do |util_config|
    util_config.vm.host_name = "util.local"
    util_config.vm.network :hostonly, "10.10.10.110"
    util_config.vm.forward_port 2003, 2003 # graphite
    util_config.vm.forward_port 2004, 2004 # graphite
    util_config.vm.forward_port 3000, 3001 # graylog2
    util_config.vm.forward_port 4567, 4567 # riemann-dash
    util_config.vm.forward_port 5555, 5555 # riemann
    util_config.vm.forward_port 7002, 7002 # graphite
    util_config.vm.forward_port 80, 8081 # graphite-web
    util_config.vm.forward_port 8080, 8082 # sensu-dashboard
    util_config.vm.provision :shell, :path => "bootstrap.sh"
  end

  config.vm.define :data do |data_config|
    data_config.vm.box = "lucid64"
    data_config.vm.host_name = "data.local"
    data_config.vm.network :hostonly, "10.10.10.120"
    data_config.vm.forward_port 5672, 5672 # rabbitmq
    data_config.vm.forward_port 6379, 6379 # redis
    data_config.vm.forward_port 8983, 8983 # solr
    data_config.vm.provision :shell, :path => "bootstrap.sh"
  end

  config.vm.define :jenkins do |jenkins_config|
    jenkins_config.vm.box = "lucid64"
    jenkins_config.vm.host_name = "jenkins.local"
    jenkins_config.vm.network :hostonly, "10.10.10.125"
    jenkins_config.vm.forward_port 8888, 8888 # jenkins
    jenkins_config.vm.provision :shell, :path => "bootstrap.sh"
  end

  config.vm.define :app do |app_config|
    app_config.vm.box = "lucid64"
    app_config.vm.host_name = "app.local"
    app_config.vm.customize ["modifyvm", :id, "--memory", 1024]
    app_config.vm.box_url = "http://files.vagrantup.com/lucid64.box"
    app_config.vm.network :hostonly, "10.10.10.115"
    app_config.vm.forward_port 80, 8080
    app_config.vm.forward_port 8000, 8000
    app_config.vm.provision :shell, :path => "bootstrap.sh"
  end

  config.vm.define :sandbox do |sb_config|
    sb_config.vm.host_name = "sandbox.local"
    sb_config.vm.customize ["modifyvm", :id, "--memory", 1024]
    sb_config.vm.network :hostonly, "10.10.10.120"
    sb_config.vm.forward_port 80, 8081 # graphite-web
    sb_config.vm.forward_port 2003, 2003 # graphite
    sb_config.vm.forward_port 2004, 2004 # graphite
    sb_config.vm.forward_port 3000, 3001 # graylog2
    sb_config.vm.forward_port 4567, 4567 # riemann-dash
    sb_config.vm.forward_port 5555, 5555 # riemann
    sb_config.vm.forward_port 5672, 5672 # rabbitmq
    sb_config.vm.forward_port 6379, 6379 # redis
    sb_config.vm.forward_port 7002, 7002 # graphite
    sb_config.vm.forward_port 8000, 8000
    sb_config.vm.forward_port 8080, 8082 # sensu-dashboard
    sb_config.vm.forward_port 8888, 8888 # jenkins
    sb_config.vm.forward_port 8983, 8983 # solr
  end
end
