name    'ehazlett-appserver'
version '0.0.1'
source ''
author 'ehazlett'
license 'Apache License, Version 2.0'
summary 'Installs and configures various appservers'
description 'Installs and configures application servers (i.e. uWSGI, node.js)'
project_page ''