name    'ehazlett-puppetdashboard'
version '0.0.1'
source 'https://github.com/ehazlett/puppet-module-puppetdashboard'
author 'ehazlett'
license 'Apache License, Version 2.0'
summary 'Installs and configures the Puppet Dashboard'
description 'Installs and configures the Puppet Dashboard'
project_page 'https://github.com/ehazlett/puppet-module-puppetdashboard'
